### ISSUE TITLE
Optional timeout

### ISSUE THREAD

**Issue by santa112358** [bazrafkan/google_place#38]
Thank you for the great package. It helps me a lot🤗

I guess the timeout 1500 mil sec is too short for some cases, so it should be set by optional. 
Is it fine for you @bazrafkan ? If so, I will make pr for this change.

**Comment by tomwyr** [comment]
`timeout` inside `GooglePlace` class is mutable which means you should be able to adjust it for your needs.

**Comment by Mayb3Nots** [comment]
Added a PR to add this feature. 

Meanwhile if you want you can use this in your `pubspec.yaml`
```
google_place:
    git:
      url: https://github.com/Mayb3Nots/google_place
      ref: master
```

However, I did some testing and found out that its faster to resend your request if its timesout rather than increasing the timeout and wait for it.
